# Regular expressions for district names per province

regexKZN1 = r"\b(port\s+shepstone|alfred|umzimkulu|ezingolweni|newcastle|dundee|glencoe|kliprivier|dannhauser|utrecht|madadeni|nqutu|emnambithi|paulpietersburg|vryheid|kwa\s+mapumulu|umvoti|kranskop|nkandla|msinga|lower\s+tugela|inkanyezi|ndwedwe|mtunzini|lower\s+umfolozi|enseleni|eshowe|ongoye|babanango|mtonjaneni|mahlabatini|simdlangentsha|ngotshe|hlabisa|nongoma|ubombo|ingwavuma|emzumbe|ixopo|umzinto|underberg|impendh?le|polela|vulindlela|vulamehlo|camperdown|umbumbulu|lions\s+river|new\s+hanover|maritzburg|mooirivier|empumalanga|durban|umlazi|pinetown|inanda|ntuzuma|est?court|weenen|okhahlamba|bergville|mount\s+currie|hluhluwe|dukuduku|bulwer|howick|mfolozi|pongola|mkuze|tugela|umhlanga|amanzimtoti|mpendh?le|pietermaritzburg)\b"

regexKZN2 = r"\b(h\.?\s*g\.?\s*r\.?|p\.?\s*m\.?\s*b\.?)\b"

regexEasternCape = r"\b(willowmore|aberdeen|hankey|humansdorp|steytlerville|jansenville|uitenhage|port\s+elizabeth|kirkwood|somerset-?\s*oos|somerset-?\s*east|pearston|cradock|graaff-?\s*reinet|hofmeyr|alexandria|albany|bedford|adelaide|tarka|peddie|bathurst|victoria\s+east|alice|fort\s+beaufort|mpofu|cathcart|mdantsane|middledrift|zwelitsha|stutterheim|keiskammahoek|hewu|whittlesea|queenstown|cacadu|glen\s+grey|lady\s+frere|sterkstroom|wodehouse|cofimvaba|st\.?\s*marks|xalanga|cala|steynsburg|molteno|venterstad|albert|aliwal-?\s*noord|aliwal-?\s*north|herschel|sterkspruit|elliot|barkly-?\s*oos|barkly-?\s*east|lady\s+grey|east\s+london|king\s+williams\s+town|joubertina|lusikisiki|bizana|siphaqeni|flagstaff|masixebeni|mt\.?\s*ayliff|[ck]{1}entani|gcuwa|butterworth|engcobo|tsomo|nqamakwe|i?dutywa|gatyana|willowvale|umtata|tsolo|mqanduli|xhora|elliotdale|komga|ngqeleni|libode|umzimvubu|port\s+st\.?\s*johns|indwe|mt\.?\s*fletcher|maclear|qumbu|kwabhaca|mt\.?\s*frere|matatiele|maluti|tabankulu|grahamstown|pirie|King\s*Wms?\s* Town|kingwilliamstown)\b"

regexFreeState = r"\b(fauresmith|koffiefontein|jacobsdal|petrusburg|philippolis|jagersfontein|bethulie|trompsburg|edenburg|rouxville|wepener|zastron|smithfield|reddersburg|bloemfontein|dewetsdorp|ladybrand|boshof|hoopstad|bultfontein|wesselsbron|brandfort|botshabelo|theunissen|thaba\s+nchu|excelsior|winburg|clocolan|welkom|odendaalsrus|bothaville|virginia|hennenman|kroonstad|ventersburg|viljoenskroon|frankfort|vrede|harrismith|ficksburg|marquard|senekal|fouriesburg|bethlehem|lindley|heilbron|vredefort|parys|reitz|witsieshoek|sasolburg)\b"

regexGauteng = r"\b(randfontein|krugersdorp|roodepoort|westonaria|kempton\s+park|germiston|johannesburg|randburg|pretoria|wonderboom|cullinan|nigel|brakpan|boksburg|benoni|springs|bronkhorstspruit|vanderbijlpark|vereeniging|soweto|alberton|melville)\b"

regexLimpopo = r"\b(soutpansberg|sekgosese|pietersburg|letaba|ritavi|naphuno|phalaborwa|bolobedu|vuwani|giyani|malamulele|namakgale|lulekani|potgietersrus|mutale|messina|dzanani|thohoyandou|sekhukhuneland|thabazimbi|warmbad|waterberg|moutse|groblersdal|ellisras|mokerong|nebo|seshego|bochum|thabamoopo|venda|zebediela)\b"

regexMpumalanga = r"\b(mapulaneng|pelgrimsrus|pilgrim'?s\s*rest|witrivier|standerton|balfour|hoeveldrift|delmas|ermelo|bethal|witbank|mbibana|mdutjana|mkobola|amersfoort|wakkerstroom|piet\s+retief|eerstehoek|lydenburg|belfast|carolina|barberton|waterval-?\s*boven|nsikazi|nkomazi|dullstroom|timbavati|nelspruit|kaapsc?h?e\s*hoop|blyde\s+riv)\b"

regexNorthWest = r"\b(vryburg|taung|christiana|schweizer-?\s*reneke|molopo|marico|ganyesa|bloemhof|wolmaransstad|klerksdorp|delareyville|ditsobotla|lichtenburg|lehurutshe|madikwe|cologny|ventersdorp|koster|potchefstroom|brits|odi|rustenburg|bafokeng|mankwe|moretele|swartruggens|oberholzer|magaliesberg)\b"

regexNorthernCape1 = r"\b(namakwaland|calvinia|sutherland|kenhardt|williston|gordonia|fraserburg|carnarvon|victoria-?\s*west|prieska|britstown|de\s+aar|hopetown|hanover|philipstown|noupoort|colesberg|postmasburg|kuruman|barkly-?\s*west?|kimberley|warrenton|hartswater|kudumane)\b"

regexNorthernCape2 = r"(namakwa|namaqua)"

regexWesternCape = r"\b(malmesbury|moorreesburg|hopefield|piketberg|tulbagh|vredenburg|vredendal|clanwilliam|vanrhynsdorp|wellington|worcester|paarl|ceres|ladismith|laingsburg|montagu|beaufort-?\s*west?|prince\s+albert|calitzdorp|oudtshoorn|murraysburg|wynberg|simonstad|goodwood|bellville|caledon|strand|kuilsrivier|stellenbosch|hermanus|bredasdorp|swellendam|robertson|riversdal|mosselbaai|mossel\s+bay|george|uniondale|knysna|outeniqua|grabouw|cape\s+town)\b"

regexNamibia = r"\b(abenab|aminuis|anamulenge|andara|ariamsvlei|asab|aus|aussenkehr|bagani|baumgartsbrunn|blouwes|brakwater|buitepos|bunya|caprivi|chinchimane|diyogha|dobra|dolfynstrand|dordabis|drimiopsis|edundja|eenhana|eheke|eiseb|ekango\s+lomuve|ekuku|epinga|epukiro|epuku|erongo|etomba|ezorongondo|fransfontein|gobabis|groot\s+aub|grunau|hardap|helmeringhausen|hoachanas|hochfeld|ibbu|iihongo|kahenge|kaisosi|kalkfeld|kangongo|karas|katima\s+mulilo|kauluma|keetmanshoop|khauxas|khomas|klein\s+aub|kombat|kongola|kosis|kunene|langstrand|lisikili|luhonono|mariental|mashare|mburuuru|mpungu|mupini|nakabolelwa|nakayale|narubis|ncamangoro|neudamm|nkurenkuru|noordoewer|odibo|ogongo|ohamaremba|ohangwena|oikango|okakundu|okalongo|okamatapati|okambonde|okamule|okanghudi|okangwati|okatana|okauva|okazapamba|okoloti|okombahe|okongo|olukonda|olupandu|omagongati|omaheke|omakango|omashekediva|omatjette|omhuuda|omitara|ompakoya|omugulugwombashe|omunduta|omungwelume|omusati|omuthiya|omutwewomedi|omutwewomunu|onamungundo|onamunhama|onandova|onawa|onayena|ondeihaluka|ondeikela|onderombapa|ondobe\s+yomunghudi|onekwaya\s+west|ongandjera|ongha|onghala|onhokolo|oniimwandi|oniiwe|onkumbula|opuwo|oshakati|oshana|oshandi|oshigambo|oshikango|oshikoto|oshindobe|oshivelo|osire|otindi|otjimbingwe|otjiwarongo|otjomuru|otjozondjupa|otshaandja|outapi|outjo|ovinjange|ovituua|rosh\s+pinah|rundu|rupara|sangwali|schlip|seeheim|seeis|sesfontein|sibbinda|snyfontein|solitaire|swakopmund|talismanus|tondoro|tsintsabis|tsjaka|tsumkwe|uibis|uis|utuseb|uuvudhiya|uuyoka|windhoek|wlotzkasbaken|namib)\b"

regexZimbabwe = r"\b(gokwe|gweru|kwekwe|marira|munyati|mvuma|redcliff|shurugwi|silobela|somabhula|vungu|zhombe|zvishavane|alisupi|brunapeg|colleen\s+bawn|esigodini|esimbomvu|figtree|filabusi|fumukwe|gwai|gwanda|hwali|kezi|lutumba|manama|marinoha|marula|mazunga|plumtree|towla|tuli|vubachikwe|west\s+nicholson|bembezi|binga|bradfield|dagamela|dete|eastnor|inyati|jotsholo|kamativi|kariyangwe|gwelo|matetsi|mbuma|mlibizi|mpandamatenga|nkayi|nyamandhlovu|baradzanwa|boora|chibwedziva|chigumisirwa|chikuku|chikukutu|chiredzi|chiremwaremwa|chirorwe|devure|felixburg|gurajena|gwengwerere|magocha|magomana|maranda|marozva|mashava|mashoko|masvingo|matibi|matsvange|mazungunye|mbizi|mukore|mungezi|mupamande|mupandawana|murwira|museti|mutikizizi|ndanga|negovano|neshuro|ngundu|nyahunda|nyarushiri|banket|caesar|chakari|charara|chegutu|chinhoyi|darwendale|eiffel\s+flats|feock|gadzema|kadoma|karoi|kildonan|kutama|madadzi|magunje|makuti|makwiro|mhangura|mubayira|muriel|murombedzi|mutorashanga|muzvezve|mwami|norton|raffingora|sanyati|selous|shackleton|tashinga|tengwe|trelawney|umsweswe|vanad|venice|vuti|arcturus|beatrice|bromley|chivhu|goromonzi|kotwa|macheke|marondera|mount\s+hampden|murewa|mutoko|nyabira|nyamapanda|rocky\s+spruit|ruwa|shinga|bindura|domboshava|guruve|jumbo|kanyemba|madziwa|manhenga|mazowe|mt\.?\s+darwin|mukumbura|mushumbi\s+pools|musweswenedi|muzarabani|birchenough\s+bridge|buhera|cashel|chimanimani|chipinge|chisumbanje|craigmore|dorowa|gumira|hauna|headlands|juliasdale|junction\s+gate|massi\s+kessi|mt\.?\s+selinda|murambinda|mutambara|mutare|umtali|nyanga|nyanyadzi|nyazura|odzi|penhalonga|rusape|sakubva|sanyatwe|stapleford|tandaai|tizvione|troutbeck|tsanzaguru|tsunga|watsomba|zimunya|chitungwiza|harare|wankie|hwange)\b"

regexBotswana = r"\b(bobonong|bokaa|chadibe|charles\s+hill|chobe|etsha|francistown|gabane|gab[aeo]{1}rones?|ghanzi|gweta|hukuntsi|jwaneng|kang|kanye|kasane|letlhakane|letlhakeng|lobatse|mahalapye|mandunyane|masunga|mathangwane|maun|maunatlala|mmadinare|mmankgodi|mmopane|mochudi|mogoditshane|molepolole|mopipi|moshupa|nata|okavango|orapa|otse|palapye|rakops|selibe\s+phikwe|serowe|shakawe|shoshong|thamaga|tlokweng|tshabong|tutume)\b"

regexMozambique = r"\b(angoche|beira|bilene|catandica|chibuto|chicualacuala|chimoio|chinde|chokwe|cuamba|gurue|inhambane|lichinga|manica|maputo|marracuene|matola|maxixe|moatize|mocimboa\s+da\s+praia|mocuba|montepuez|mueda|naamcha|nacala|nampula|palma|pemba|ponta\s+d'?ouro|quelimane|tete|vilankulo|xai-?\s*xai|zavala)\b"

regexAngola = r"\b(ambriz|andulo|bailundo|balombo|baia\s+farta|benguela|bibala|vila\s+arriaga|m'?bimbi|bimbe|biula|bungo|cabamba|cabinda|kabinda|caboledo|cacolo|caconda|caculama|cacuso|cafunfo|cahama|caiengue|caimbambo|calandala|calenga|kalenga|calonda|calucinga|calulo|caluquembe|kalukembe|camabatela|camacupa|general\s+machado|vila\s+general\s+machado|camanongue|bucaco|kamenongue|camaxilo|cambambe|cambongue|cambundi|nova\s+gaia\s+|catembo|camissombo|verissimo\s+sarmento|candjimbe|cangamba|vila\s+de\s+aljustrel|cangandala|cangumbe|capelongo|cubango|kuvango|capenda\s+camulemba|capulo|cassanguide|cassanguidi|cassongue|catabola|katabola|nova\s+sintra|catacanha|catchiungo|katchiungo|katchungo|cantchiungo|catumbela|caungula|caxita\s+cameia|caxito|cazaje|cazage|cazombo|caala|kaala|kahala|cela|chiange|gambos|chibanda|chibemba|chibia|chicala|chingufo|chipindo|chissamba|chitado|chitembo|coemba|colui|candingo|conda|cota|coutada|cuangar|cuango-?\s*luzamba|kwango|luzamba|cuango|cuasa|cubal|cuchi|cuilo|cuima|cuimba|cuito\s+cuanavale|cuvelai|dala|damba|didimbo|dombe\s+grande|dongo|dundo|chitato|ekunha|vila\s+flor|folgares|funda|gabela|galo|ganda|golungo\s+alto|guri|huambo|nova\s+lisboa|humpata|jamba|kuito|bie|silva\s+porto|leua|lobito|lombe|longa|longonjo|luacano|dilolo|luanda|loanda|sao\s+paulo\s+de\s+loanda|luau|vila\s+teixeira\s+de\s+sousa|lubango|sa\s+da\s+bandeira|lucala|lucapa|lukapa|lucusse|luena|lwena|luso|vila\s+luso|luiana|luimbale|londuimbali|luma\s+cassao|lumbala\s+n'?guimbo|lumbala|lumeje|luremo|luxilo|landana|cacongo|malanje|malange|malembo|maludi|marimba|marimbanguengo|massango|matala|mavinga|mbanza-?\s*congo|m'?banza-?\s*kongo|sao\s+salvador|sao\s+salvador\s+do\s+congo|menongue|vila\s+serpa|pinto|serpa\s+pinto|muchinda|muconda|nova\s+chaves|mucumbo|mucusso|mucussueje|muginga|mulondo|mungo|munhango|mussende|musserra|mafuca|mussuco|n'?dalatando|vila\s+salazar|n'?zeto|nzeto|ambrizete|namacunde|santa\s+clara|mocamedes|negage|nharea|noqui|nzagi|andrada|ondjiva|pinheiro|porto\s+amboim|gunza|quela|quibala|kibala|quibaxe|quicombo|kikombo|quilengues|quimavongo|qu|quipungo|quirima|quimbango|quimbele|saco?\s*mar|samunona|saurimo|henrique\s+de\s+carvalho|savate|savungo|songo|soyo|santo\s+antonio\s+do\s+zaire|sumbe|novo\s+redondo|tchindjenje|quingenge|tchipelongo|techamutete|chamutete|tentativa|tombua|tomboa|tombwa|tombwe|porto\s+alexandre|tumba|uku|vila\s+nova\s+do\s+seles|ukuma|cuma|uige|uije|carmona|vila\s+marechal\s+carmona|viana|waku\s+kungo|waku\s+kundo|santa\s+comba|buandangue|uaco\s+cungo|xangongo|vila\s+ro[cz]{1}ades|xa-?\s*muteba)\b"

regexZambia = r"/\b(chadiza|chama|chambeshi|chavuma|chembe|chibombo|chiengi|chilubi|chililabombwe|chinsali|chinyingi|chisamba|choma|gwembe|isoka|kabompo|kafue|kafulwe|kalabo|kalene\s+hill|kalomo|kalulushi|kanyembo|kaoma|kapiri\s+mposhi|kasempa|kashikishi|kataba|katete|kawambwa|kazembe|mwansabombwe|kibombomene|luangwa|lufwanyama|lukulu|lundazi|macha\s+mission|makeni|mansa|mazabuka|mbala|mbereshi|mfuwe|milenge|misisi|mkushi|mongu|monze|mpika|mporokoso|mpulungu|mumbwa|muyombe|mwinilunga|nchelenge|ngoma|nkana|nseluka|petauke|samfya|senanga|serenje|sesheke|shiwa\s+ngandu|siavonga|sikalongo|sinazongwe|solwezi|zimba)\b"

regexMalawi = r"\b(balaka|bangula|blantyre|chikwawa|chilumba|chintheche|chipoka|chiradzulu|chitipa|chiwembe|dedza|domasi|dowa|ekwendeni|embangweni|karonga|kasungu|likoma|lilongwe|limbe|livingstonia|liwonde|luchenza|machinga|malosa|mangochi|mchinji|monkey\s+bay|mponela|mua|mulanje|mzimba|mzuzu|namitete|nathenje|njata|nkhata\s+bay|nkhoma|nkhotakota|nsanje|ntcheu|ntchisi|phalombe|rumphi|salima|thyolo|zalewa|zomba)\b"